version: '3.8'
services:
  parser:
    build:
      context: .
      dockerfile: docker/dev/parser.dockerfile
    image: hircum-triticum-parser
    container_name: hircum-triticum-parser
    command: go run github.com/quercus-insolita/hircum-triticum/cmd/parser
    ports:
      - 9427:9427
    volumes:
      - ./go.mod:/go/src/app/go.mod
      - ./go.sum:/go/src/app/go.sum
      - ./cmd:/go/src/app/cmd
      - ./internal:/go/src/app/internal
networks:
  default:
    name: hircum-triticum-default
