version: '3.8'
x-parser: &x-parser
  image: hircum-triticum-parser
  entrypoint: go run github.com/quercus-insolita/hircum-triticum/cmd/parser
  volumes:
    - ./go.mod:/go/src/app/go.mod
    - ./go.sum:/go/src/app/go.sum
    - ./cmd:/go/src/app/cmd
    - ./internal:/go/src/app/internal
    - ./logs:/go/src/app/logs
services:
  parser:
    <<: *x-parser
    build:
      context: .
      dockerfile: docker/dev/parser.dockerfile
    container_name: hircum-triticum-parser
    ports:
      - 9427:9427
  parser-auchan:
    <<: *x-parser
    container_name: hircum-triticum-parser-auchan
    command: -parser auchan -port 29116
    ports:
      - 29116:29116
  parser-aquamarket:
    <<: *x-parser
    container_name: hircum-triticum-parser-aquamarket
    command: -parser aquamarket -port 29117
    ports:
      - 29117:29117
  parser-fozzy:
    <<: *x-parser
    container_name: hircum-triticum-parser-fozzy
    command: -parser fozzy -port 29118
    ports:
      - 29118:29118
  api:
    image: hircum-triticum-api
    volumes:
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
#      - ./src:/app/src
    build:
      context: .
      dockerfile: docker/dev/api.dockerfile
    command: npm start
    container_name: hircum-triticum-api
    ports:
      - 29115:29115
    depends_on:
      - parser-aquamarket
      - parser-fozzy
      - parser-auchan
networks:
  default:
    name: hircum-triticum-default
